import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { cookies } from "next/headers";
import ClientLayout from "@/components/ui/client-layout";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CookiesTheme = await cookies();

  const theme = CookiesTheme.get("theme")?.value; // "light" | "dark" | undefined
  // If cookie is missing, we do NOT set data-theme so system preference applies.
  const dataTheme = theme === "light" || theme === "dark" ? theme : undefined;

  return (
    <html lang="en" data-theme={dataTheme}>
      <body>
        <ClientLayout>{children}</ClientLayout>

        <Toaster
          toastOptions={{
            style: {
              // fontFamily: "'Jost', sans-serif",
              fontSize: "12px",
              fontWeight: "700",
            },
            success: {
              // iconTheme: {
              //   primary: "#1a2433",
              //   secondary: "#ffffff",
              // },
            },
          }}
        />
      </body>
    </html>
  );
}
