import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { cookies } from "next/headers";
import ClientLayout from "@/components/ui/client-layout";
import { Toaster } from "react-hot-toast";
import { WsProvider } from "@/contexts/ws-context";
import { ACCESS_COOKIE } from "@/utils/tokens";
import UserProvider from "@/contexts/user-cintext";
import QueryProviders from "@/contexts/query-client-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CookiesTheme = await cookies();

  const theme = await CookiesTheme.get("theme")?.value; // "light" | "dark" | undefined
  // If cookie is missing, we do NOT set data-theme so system preference applies.
  const dataTheme = theme === "light" || theme === "dark" ? theme : undefined;

  const token = CookiesTheme.get(ACCESS_COOKIE)?.value;

  return (
    <html lang="en" data-theme={dataTheme}>
      <body>
        <QueryProviders>
          <WsProvider token={token ?? ""}>
            <UserProvider token={token ?? ""}>
              <ClientLayout>{children}</ClientLayout>
            </UserProvider>
          </WsProvider>
        </QueryProviders>

        <Toaster
          toastOptions={{
            style: {
              // fontFamily: "'Jost', sans-serif",
              fontSize: "12px",
              fontWeight: "700",
            },
            success: {
              // iconTheme: {
              //   primary: "#1a2433",
              //   secondary: "#ffffff",
              // },
            },
          }}
        />
      </body>
    </html>
  );
}
